### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by alexandernst** [dominictarr/config-chain#21]
The `package.json` states that this lib is `v1.1.8`, but the latest tag is `v1.1.1`. Please fix.

**Comment by dominictarr** [comment]
fixed, and also published 1.1.9 from https://github.com/dominictarr/config-chain/pull/20

**Comment by dominictarr** [comment]
fixed, and also published 1.1.9 from https://github.com/dominictarr/config-chain/pull/20
